version: "3"
services:
  fony:
    build: .
    container_name: fony-default
    networks:
      - local_default
    ports:
      - "8888:80"
    volumes:
      - .:/go/src/github.com/schigh/fony
    environment:
      - GOBIN=/go/bin
    command: ["fony", "-f", "sample/sample.json"]

networks:
  local_default:
    external: true
