package domain

/* generated by slices (github.com/schigh/slices).  do not edit. */
/* gen date: Mon, 12 Nov 2018 22:44:26 -0500 */

// ResponseSlice aliases []Response
type ResponseSlice []Response

// Value returns the wrapped Response slice
func (slice ResponseSlice) Value() []Response {
	return []Response(slice)
}

// Map applies a function to every Response in the slice.  This function will mutate the slice in place
func (slice ResponseSlice) Map(f func(*Response) *Response) {
	for i := 0; i < len(slice); i++ {
		v := f(&slice[i])
		slice[i] = *v
	}
}

// Filter evaluates every element in the slice, and returns all Response
// instances where the eval function returns true
func (slice ResponseSlice) Filter(f func(*Response) bool) ResponseSlice {
	out := make([]Response, 0, len(slice))
	for i := 0; i < len(slice); i++ {
		if f(&slice[i]) {
			out = append(out, slice[i])
		}
	}

	return ResponseSlice(out)
}

// Each applies a function to every Response in the slice.
func (slice ResponseSlice) Each(f func(*Response)) {
	for i := 0; i < len(slice); i++ {
		f(&slice[i])
	}
}

// TryEach applies a function to every Response in the slice,
// and returns the index of the element that caused the first error, and the error itself.
// If every member of the slice returns nil, this function will return (-1, nil)
// The iteration will halt on the first error encountered and return it.
func (slice ResponseSlice) TryEach(f func(*Response) error) (int, error) {
	for i := 0; i < len(slice); i++ {
		if err := f(&slice[i]); err != nil {
			return i, err
		}
	}

	return -1, nil
}

// IfEach applies a function to every Response in the slice,
// and returns the index of the element that caused the function to return false.
// If every member of the slice evaluates to true, this function will return (-1, true)
// The iteration will halt on the first false return from the function.
func (slice ResponseSlice) IfEach(f func(*Response) bool) (int, bool) {
	for i := 0; i < len(slice); i++ {
		if !f(&slice[i]) {
			return i, false
		}
	}

	return -1, false
}
